# Generated by Django 5.2.17 on 2026-08-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EMPLOYMENT_STATUS',
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employment_status',
            field=models.ForeignKey(db_column='employment_status_id', on_delete=django.db.models.deletion.PROTECT, to='core.employmentstatus'),
        ),
    ]
