import '../styles/ReportsPage.css'

const ReportsPage = ({ onNavigate }) => {
  return (
    <div className="screen stack">

      {/* Report cards */}
      <div className="report-cards">
        <div className="report-card">
          <div className="report-card-top">
            <div className="report-card-title">Teaching Load Summary</div>
            <span className="badge badge-slate">Not Generated</span>
          </div>
          <div className="report-card-desc">
            Full breakdown of teacher-subject-section assignments for the active school year.
          </div>
          <div className="report-card-actions">
            <button className="btn btn-outline btn-sm btn-full">Preview</button>
            <button className="btn btn-primary btn-sm btn-full">Export PDF</button>
          </div>
        </div>

        <div className="report-card">
          <div className="report-card-top">
            <div className="report-card-title">Unassigned Load Report</div>
            <span className="badge badge-slate">Not Generated</span>
          </div>
          <div className="report-card-desc">
            Subjects and sections with no assigned teacher (requires manual review.)
          </div>
          <div className="report-card-actions">
            <button className="btn btn-outline btn-sm btn-full">Preview</button>
            <button className="btn btn-primary btn-sm btn-full">Export PDF</button>
          </div>
        </div>

        <div className="report-card">
          <div className="report-card-top">
            <div className="report-card-title">Workload Balance Report</div>
            <span className="badge badge-green">Available</span>
          </div>
          <div className="report-card-desc">
            Comparison of assigned hours per teacher against maximum load capacity.
          </div>
          <div className="report-card-actions">
            <button
              className="btn btn-outline btn-sm btn-full"
              onClick={() => { onNavigate && onNavigate('workload-dashboard') }}
            >
              View Dashboard
            </button>
            <button className="btn btn-primary btn-sm btn-full">Export PDF</button>
          </div>
        </div>
      </div>

      {/* History table */}
      <div className="card card-body">
        <div className="section-title">Generated Load History</div>
        <div className="table-wrap report-history-table">
          <table className="data-table">
            <thead>
              <tr>
                <th>Date Generated</th>
                <th>School Year</th>
                <th>Level</th>
                <th>Scope</th>
                <th>Generated By</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td colSpan={6} className="table-empty-cell">
                  No records found. Generate a teaching load to see history here.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  )
}

export default ReportsPage
