# Generated by Django 5.2.17 on 2026-08-06 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('grade_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'GRADE_LEVEL',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('deped_school_id', models.CharField(max_length=20, unique=True)),
                ('school_name', models.CharField(max_length=150)),
                ('school_level', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SCHOOL',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('school_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
            ],
            options={
                'db_table': 'SCHOOL_YEAR',
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('strand_id', models.AutoField(primary_key=True, serialize=False)),
                ('strand_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'STRAND',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'SUBJECT',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TRACK',
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('offering_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_per_week', models.FloatField()),
                ('grade_level', models.ForeignKey(db_column='grade_level_id', on_delete=django.db.models.deletion.CASCADE, to='core.gradelevel')),
                ('strand', models.ForeignKey(blank=True, db_column='strand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.strand')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'db_table': 'SUBJECT_OFFERING',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('employment_status', models.CharField(choices=[('Permanent', 'Permanent'), ('Provisional', 'Provisional'), ('Part-time', 'Part-time')], max_length=50)),
                ('max_load_hours', models.FloatField()),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'db_table': 'TEACHER',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('grade_level', models.ForeignKey(db_column='grade_level_id', on_delete=django.db.models.deletion.CASCADE, to='core.gradelevel')),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('school_year', models.ForeignKey(db_column='school_year_id', on_delete=django.db.models.deletion.CASCADE, to='core.schoolyear')),
                ('strand', models.ForeignKey(blank=True, db_column='strand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.strand')),
                ('adviser_teacher', models.ForeignKey(blank=True, db_column='adviser_teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_sections', to='core.teacher')),
            ],
            options={
                'db_table': 'SECTION',
            },
        ),
        migrations.CreateModel(
            name='TeachingLoad',
            fields=[
                ('load_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('offering', models.ForeignKey(db_column='offering_id', on_delete=django.db.models.deletion.CASCADE, to='core.subjectoffering')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, to='core.section')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'db_table': 'TEACHING_LOAD',
            },
        ),
        migrations.AddField(
            model_name='strand',
            name='track',
            field=models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, to='core.track'),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'db_table': 'USER_ACCOUNT',
            },
        ),
        migrations.CreateModel(
            name='TeacherSpecialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'db_table': 'TEACHER_SPECIALIZATION',
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
