# Generated by Django 5.2 on 2026-09-07 01:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Employment Status',
                'verbose_name_plural': 'Employment Statuses',
                'db_table': 'EMPLOYMENT_STATUS',
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('grade_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_closed', models.DateField(default='9999-12-31')),
            ],
            options={
                'db_table': 'GRADE_LEVEL',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('deped_school_id', models.CharField(max_length=20, unique=True)),
                ('school_name', models.CharField(max_length=150)),
                ('school_level', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SCHOOL',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('school_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one SchoolYear should be active at a time; switching is a manual action performed by the principal.')),
            ],
            options={
                'db_table': 'SCHOOL_YEAR',
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('strand_id', models.AutoField(primary_key=True, serialize=False)),
                ('strand_name', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_closed', models.DateField(default='9999-12-31')),
            ],
            options={
                'db_table': 'STRAND',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_closed', models.DateField(default='9999-12-31')),
            ],
            options={
                'db_table': 'SUBJECT',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_closed', models.DateField(default='9999-12-31')),
            ],
            options={
                'db_table': 'TRACK',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('school', models.ForeignKey(blank=True, db_column='school_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'db_table': 'USER_ACCOUNT',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('offering_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_per_week', models.FloatField()),
                ('grade_level', models.ForeignKey(db_column='grade_level_id', on_delete=django.db.models.deletion.CASCADE, to='core.gradelevel')),
                ('strand', models.ForeignKey(blank=True, db_column='strand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.strand')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'db_table': 'SUBJECT_OFFERING',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('house_no_street', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('city_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employment_status', models.ForeignKey(db_column='employment_status_id', on_delete=django.db.models.deletion.PROTECT, to='core.employmentstatus')),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'db_table': 'TEACHER',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('grade_level', models.ForeignKey(db_column='grade_level_id', on_delete=django.db.models.deletion.CASCADE, to='core.gradelevel')),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('school_year', models.ForeignKey(db_column='school_year_id', on_delete=django.db.models.deletion.CASCADE, to='core.schoolyear')),
                ('strand', models.ForeignKey(blank=True, db_column='strand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.strand')),
                ('adviser_teacher', models.ForeignKey(blank=True, db_column='adviser_teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_sections', to='core.teacher')),
            ],
            options={
                'db_table': 'SECTION',
            },
        ),
        migrations.CreateModel(
            name='TeacherLoadLimit',
            fields=[
                ('load_limit_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_load_hours', models.FloatField()),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField(default='9999-12-31')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='load_limits', to='core.teacher')),
            ],
            options={
                'db_table': 'TEACHER_LOAD_LIMIT',
            },
        ),
        migrations.CreateModel(
            name='TeachingLoad',
            fields=[
                ('load_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(help_text="e.g. 'Monday' or 'MWF'", max_length=20)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('room_assigned', models.CharField(blank=True, max_length=50, null=True)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('offering', models.ForeignKey(db_column='offering_id', on_delete=django.db.models.deletion.CASCADE, to='core.subjectoffering')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, to='core.section')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'db_table': 'TEACHING_LOAD',
            },
        ),
        migrations.AddField(
            model_name='strand',
            name='track',
            field=models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, to='core.track'),
        ),
        migrations.CreateModel(
            name='TeacherSpecialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField(default='9999-12-31')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'db_table': 'TEACHER_SPECIALIZATION',
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
