# Generated by Django 5.2 on 2026-09-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school',
            new_name='school_id',
        ),
    ]
