# Generated by Django 5.2 on 2026-09-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_school_user_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_id',
            field=models.ForeignKey(blank=True, db_column='school_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='School'),
        ),
    ]
