# Generated by Django 6.1 on 2026-09-23 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_school_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('education_level', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=50, null=True)),
                ('strand', models.CharField(blank=True, max_length=50, null=True)),
                ('algorithm', models.CharField(choices=[('greedy', 'Greedy'), ('backtracking', 'Backtracking')], max_length=20)),
                ('assigned_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('already_assigned_count', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, db_column='generated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_logs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('school_year', models.ForeignKey(blank=True, db_column='school_year_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schoolyear')),
            ],
            options={
                'db_table': 'GENERATION_LOG',
                'ordering': ['-generated_at'],
            },
        ),
    ]
