# Generated by Django 6.1 on 2026-09-30 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_generationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherspecialization',
            name='strand',
            field=models.ForeignKey(blank=True, db_column='strand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.strand'),
        ),
    ]
